/*
 * GriffNode API
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.griffnode.sdk.api;

import com.griffnode.sdk.ApiException;
import com.griffnode.sdk.model.Error;
import com.griffnode.sdk.model.GetAccount200Response;
import com.griffnode.sdk.model.GetStats200Response;
import com.griffnode.sdk.model.ListBalances200Response;
import com.griffnode.sdk.model.ListInvoices200Response;
import com.griffnode.sdk.model.ListPlans200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountApi
 */
@Disabled
public class AccountApiTest {

    private final AccountApi api = new AccountApi();

    /**
     * Merchant plan, usage and limits
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAccountTest() throws ApiException {
        GetAccount200Response response = api.getAccount();
        // TODO: test validations
    }

    /**
     * Merchant transaction analytics
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getStatsTest() throws ApiException {
        GetStats200Response response = api.getStats();
        // TODO: test validations
    }

    /**
     * On-platform balances (for overage/top-up; NOT crypto settlement)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listBalancesTest() throws ApiException {
        ListBalances200Response response = api.listBalances();
        // TODO: test validations
    }

    /**
     * GriffNode billing invoices (platform ↔ merchant)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listInvoicesTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        ListInvoices200Response response = api.listInvoices(limit, offset);
        // TODO: test validations
    }

    /**
     * Plan catalogue and pricing
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listPlansTest() throws ApiException {
        ListPlans200Response response = api.listPlans();
        // TODO: test validations
    }

}
