/*
 * CryptoGate API
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…`, or `sk_test_…` for sandbox). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package live.cryptogate.sdk.api;

import live.cryptogate.sdk.ApiCallback;
import live.cryptogate.sdk.ApiClient;
import live.cryptogate.sdk.ApiException;
import live.cryptogate.sdk.ApiResponse;
import live.cryptogate.sdk.Configuration;
import live.cryptogate.sdk.Pair;
import live.cryptogate.sdk.ProgressRequestBody;
import live.cryptogate.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import live.cryptogate.sdk.model.Error;
import live.cryptogate.sdk.model.GetAccount200Response;
import live.cryptogate.sdk.model.GetStats200Response;
import live.cryptogate.sdk.model.ListBalances200Response;
import live.cryptogate.sdk.model.ListInvoices200Response;
import live.cryptogate.sdk.model.ListPlans200Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AccountApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AccountApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AccountApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getAccount
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Account details. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAccountCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/account";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "SecretKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAccountValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getAccountCall(_callback);

    }

    /**
     * Merchant plan, usage and limits
     * 
     * @return GetAccount200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Account details. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public GetAccount200Response getAccount() throws ApiException {
        ApiResponse<GetAccount200Response> localVarResp = getAccountWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Merchant plan, usage and limits
     * 
     * @return ApiResponse&lt;GetAccount200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Account details. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetAccount200Response> getAccountWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getAccountValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<GetAccount200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Merchant plan, usage and limits (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Account details. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAccountAsync(final ApiCallback<GetAccount200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAccountValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<GetAccount200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getStats
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Stats. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getStatsCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/stats";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "SecretKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getStatsValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getStatsCall(_callback);

    }

    /**
     * Merchant transaction analytics
     * 
     * @return GetStats200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Stats. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public GetStats200Response getStats() throws ApiException {
        ApiResponse<GetStats200Response> localVarResp = getStatsWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Merchant transaction analytics
     * 
     * @return ApiResponse&lt;GetStats200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Stats. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetStats200Response> getStatsWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getStatsValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<GetStats200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Merchant transaction analytics (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Stats. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getStatsAsync(final ApiCallback<GetStats200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getStatsValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<GetStats200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listBalances
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Balances. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listBalancesCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/balances";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "SecretKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listBalancesValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return listBalancesCall(_callback);

    }

    /**
     * On-platform balances (for overage/top-up; NOT crypto settlement)
     * 
     * @return ListBalances200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Balances. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public ListBalances200Response listBalances() throws ApiException {
        ApiResponse<ListBalances200Response> localVarResp = listBalancesWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * On-platform balances (for overage/top-up; NOT crypto settlement)
     * 
     * @return ApiResponse&lt;ListBalances200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Balances. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ListBalances200Response> listBalancesWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = listBalancesValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<ListBalances200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * On-platform balances (for overage/top-up; NOT crypto settlement) (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Balances. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listBalancesAsync(final ApiCallback<ListBalances200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = listBalancesValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<ListBalances200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listInvoices
     * @param limit  (optional, default to 20)
     * @param offset  (optional, default to 0)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Invoices. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listInvoicesCall(Integer limit, Integer offset, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/invoices";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "SecretKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listInvoicesValidateBeforeCall(Integer limit, Integer offset, final ApiCallback _callback) throws ApiException {
        return listInvoicesCall(limit, offset, _callback);

    }

    /**
     * CryptoGate billing invoices (platform ↔ merchant)
     * 
     * @param limit  (optional, default to 20)
     * @param offset  (optional, default to 0)
     * @return ListInvoices200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Invoices. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public ListInvoices200Response listInvoices(Integer limit, Integer offset) throws ApiException {
        ApiResponse<ListInvoices200Response> localVarResp = listInvoicesWithHttpInfo(limit, offset);
        return localVarResp.getData();
    }

    /**
     * CryptoGate billing invoices (platform ↔ merchant)
     * 
     * @param limit  (optional, default to 20)
     * @param offset  (optional, default to 0)
     * @return ApiResponse&lt;ListInvoices200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Invoices. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ListInvoices200Response> listInvoicesWithHttpInfo(Integer limit, Integer offset) throws ApiException {
        okhttp3.Call localVarCall = listInvoicesValidateBeforeCall(limit, offset, null);
        Type localVarReturnType = new TypeToken<ListInvoices200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * CryptoGate billing invoices (platform ↔ merchant) (asynchronously)
     * 
     * @param limit  (optional, default to 20)
     * @param offset  (optional, default to 0)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Invoices. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listInvoicesAsync(Integer limit, Integer offset, final ApiCallback<ListInvoices200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = listInvoicesValidateBeforeCall(limit, offset, _callback);
        Type localVarReturnType = new TypeToken<ListInvoices200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listPlans
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Plans. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listPlansCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/plans";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "SecretKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listPlansValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return listPlansCall(_callback);

    }

    /**
     * Plan catalogue and pricing
     * 
     * @return ListPlans200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Plans. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public ListPlans200Response listPlans() throws ApiException {
        ApiResponse<ListPlans200Response> localVarResp = listPlansWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Plan catalogue and pricing
     * 
     * @return ApiResponse&lt;ListPlans200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Plans. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ListPlans200Response> listPlansWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = listPlansValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<ListPlans200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Plan catalogue and pricing (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Plans. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listPlansAsync(final ApiCallback<ListPlans200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = listPlansValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<ListPlans200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
