/*
 * CryptoGate API
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…`, or `sk_test_…` for sandbox). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package live.cryptogate.sdk.api;

import live.cryptogate.sdk.ApiCallback;
import live.cryptogate.sdk.ApiClient;
import live.cryptogate.sdk.ApiException;
import live.cryptogate.sdk.ApiResponse;
import live.cryptogate.sdk.Configuration;
import live.cryptogate.sdk.Pair;
import live.cryptogate.sdk.ProgressRequestBody;
import live.cryptogate.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import live.cryptogate.sdk.model.WebhookPayload;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DefaultApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public DefaultApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DefaultApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for paymentWebhook
     * @param webhookPayload  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledge within 15s. Non-2xx is retried with backoff. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call paymentWebhookCall(WebhookPayload webhookPayload, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = webhookPayload;

        // create path and map variables
        String localVarPath = "/paymentEvent";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "SecretKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call paymentWebhookValidateBeforeCall(WebhookPayload webhookPayload, final ApiCallback _callback) throws ApiException {
        return paymentWebhookCall(webhookPayload, _callback);

    }

    /**
     * Payment lifecycle event delivered to the merchant&#39;s webhook URL
     * Signed with HMAC-SHA256 over the RAW request body. Verify by comparing &#x60;X-CryptoGate-Signature: sha256&#x3D;&lt;hex&gt;&#x60; to &#x60;hex(hmac_sha256(webhook_secret, raw_body))&#x60; using a constant-time compare. Also sent: &#x60;X-CryptoGate-Event&#x60; (the event type) and &#x60;X-Webhook-ID&#x60; (unique delivery id — use for idempotency). 
     * @param webhookPayload  (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledge within 15s. Non-2xx is retried with backoff. </td><td>  -  </td></tr>
     </table>
     */
    public void paymentWebhook(WebhookPayload webhookPayload) throws ApiException {
        paymentWebhookWithHttpInfo(webhookPayload);
    }

    /**
     * Payment lifecycle event delivered to the merchant&#39;s webhook URL
     * Signed with HMAC-SHA256 over the RAW request body. Verify by comparing &#x60;X-CryptoGate-Signature: sha256&#x3D;&lt;hex&gt;&#x60; to &#x60;hex(hmac_sha256(webhook_secret, raw_body))&#x60; using a constant-time compare. Also sent: &#x60;X-CryptoGate-Event&#x60; (the event type) and &#x60;X-Webhook-ID&#x60; (unique delivery id — use for idempotency). 
     * @param webhookPayload  (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledge within 15s. Non-2xx is retried with backoff. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> paymentWebhookWithHttpInfo(WebhookPayload webhookPayload) throws ApiException {
        okhttp3.Call localVarCall = paymentWebhookValidateBeforeCall(webhookPayload, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Payment lifecycle event delivered to the merchant&#39;s webhook URL (asynchronously)
     * Signed with HMAC-SHA256 over the RAW request body. Verify by comparing &#x60;X-CryptoGate-Signature: sha256&#x3D;&lt;hex&gt;&#x60; to &#x60;hex(hmac_sha256(webhook_secret, raw_body))&#x60; using a constant-time compare. Also sent: &#x60;X-CryptoGate-Event&#x60; (the event type) and &#x60;X-Webhook-ID&#x60; (unique delivery id — use for idempotency). 
     * @param webhookPayload  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Acknowledge within 15s. Non-2xx is retried with backoff. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call paymentWebhookAsync(WebhookPayload webhookPayload, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = paymentWebhookValidateBeforeCall(webhookPayload, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
