/*
 * CryptoGate API
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package live.cryptogate.sdk.api;

import live.cryptogate.sdk.ApiCallback;
import live.cryptogate.sdk.ApiClient;
import live.cryptogate.sdk.ApiException;
import live.cryptogate.sdk.ApiResponse;
import live.cryptogate.sdk.Configuration;
import live.cryptogate.sdk.Pair;
import live.cryptogate.sdk.ProgressRequestBody;
import live.cryptogate.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import live.cryptogate.sdk.model.CryptoSymbol;
import live.cryptogate.sdk.model.Error;
import live.cryptogate.sdk.model.GetHealth200Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SystemApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public SystemApi() {
        this(Configuration.getDefaultApiClient());
    }

    public SystemApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getHealth
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service status (intentionally NOT wrapped in the success envelope). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getHealthCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/health";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getHealthValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getHealthCall(_callback);

    }

    /**
     * API health check
     * 
     * @return GetHealth200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service status (intentionally NOT wrapped in the success envelope). </td><td>  -  </td></tr>
     </table>
     */
    public GetHealth200Response getHealth() throws ApiException {
        ApiResponse<GetHealth200Response> localVarResp = getHealthWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * API health check
     * 
     * @return ApiResponse&lt;GetHealth200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service status (intentionally NOT wrapped in the success envelope). </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetHealth200Response> getHealthWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getHealthValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<GetHealth200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * API health check (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service status (intentionally NOT wrapped in the success envelope). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getHealthAsync(final ApiCallback<GetHealth200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getHealthValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<GetHealth200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for hostedCheckoutRedirect
     * @param pk Publishable key, pk_live_… / pk_test_… (required)
     * @param amount Fiat amount (≥ 1.00 USD equivalent). (required)
     * @param crypto  (required)
     * @param link Payment-link slug for attribution. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 302 </td><td> Redirect to https://cryptogate.live/transaction/{transaction_id} </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation error (INVALID_REQUEST, INVALID_CRYPTO, INVALID_AMOUNT, AMOUNT_TOO_LOW, INVALID_CURRENCY, INVALID_METADATA, WALLET_NOT_CONFIGURED, MISSING_ITEMS, MISSING_ORDER_ID, …). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call hostedCheckoutRedirectCall(String pk, String amount, CryptoSymbol crypto, String link, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/pay";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (pk != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("pk", pk));
        }

        if (amount != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("amount", amount));
        }

        if (crypto != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("crypto", crypto));
        }

        if (link != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("link", link));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call hostedCheckoutRedirectValidateBeforeCall(String pk, String amount, CryptoSymbol crypto, String link, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'pk' is set
        if (pk == null) {
            throw new ApiException("Missing the required parameter 'pk' when calling hostedCheckoutRedirect(Async)");
        }

        // verify the required parameter 'amount' is set
        if (amount == null) {
            throw new ApiException("Missing the required parameter 'amount' when calling hostedCheckoutRedirect(Async)");
        }

        // verify the required parameter 'crypto' is set
        if (crypto == null) {
            throw new ApiException("Missing the required parameter 'crypto' when calling hostedCheckoutRedirect(Async)");
        }

        return hostedCheckoutRedirectCall(pk, amount, crypto, link, _callback);

    }

    /**
     * Hosted-checkout redirect (browser flow, publishable key)
     * Browser-facing redirect to the hosted payment page, authenticated by a **publishable** key in the query string (safe to expose client-side). Not used by the server-side SDKs — included for completeness. 
     * @param pk Publishable key, pk_live_… / pk_test_… (required)
     * @param amount Fiat amount (≥ 1.00 USD equivalent). (required)
     * @param crypto  (required)
     * @param link Payment-link slug for attribution. (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 302 </td><td> Redirect to https://cryptogate.live/transaction/{transaction_id} </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation error (INVALID_REQUEST, INVALID_CRYPTO, INVALID_AMOUNT, AMOUNT_TOO_LOW, INVALID_CURRENCY, INVALID_METADATA, WALLET_NOT_CONFIGURED, MISSING_ITEMS, MISSING_ORDER_ID, …). </td><td>  -  </td></tr>
     </table>
     */
    public void hostedCheckoutRedirect(String pk, String amount, CryptoSymbol crypto, String link) throws ApiException {
        hostedCheckoutRedirectWithHttpInfo(pk, amount, crypto, link);
    }

    /**
     * Hosted-checkout redirect (browser flow, publishable key)
     * Browser-facing redirect to the hosted payment page, authenticated by a **publishable** key in the query string (safe to expose client-side). Not used by the server-side SDKs — included for completeness. 
     * @param pk Publishable key, pk_live_… / pk_test_… (required)
     * @param amount Fiat amount (≥ 1.00 USD equivalent). (required)
     * @param crypto  (required)
     * @param link Payment-link slug for attribution. (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 302 </td><td> Redirect to https://cryptogate.live/transaction/{transaction_id} </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation error (INVALID_REQUEST, INVALID_CRYPTO, INVALID_AMOUNT, AMOUNT_TOO_LOW, INVALID_CURRENCY, INVALID_METADATA, WALLET_NOT_CONFIGURED, MISSING_ITEMS, MISSING_ORDER_ID, …). </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> hostedCheckoutRedirectWithHttpInfo(String pk, String amount, CryptoSymbol crypto, String link) throws ApiException {
        okhttp3.Call localVarCall = hostedCheckoutRedirectValidateBeforeCall(pk, amount, crypto, link, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Hosted-checkout redirect (browser flow, publishable key) (asynchronously)
     * Browser-facing redirect to the hosted payment page, authenticated by a **publishable** key in the query string (safe to expose client-side). Not used by the server-side SDKs — included for completeness. 
     * @param pk Publishable key, pk_live_… / pk_test_… (required)
     * @param amount Fiat amount (≥ 1.00 USD equivalent). (required)
     * @param crypto  (required)
     * @param link Payment-link slug for attribution. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 302 </td><td> Redirect to https://cryptogate.live/transaction/{transaction_id} </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Validation error (INVALID_REQUEST, INVALID_CRYPTO, INVALID_AMOUNT, AMOUNT_TOO_LOW, INVALID_CURRENCY, INVALID_METADATA, WALLET_NOT_CONFIGURED, MISSING_ITEMS, MISSING_ORDER_ID, …). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call hostedCheckoutRedirectAsync(String pk, String amount, CryptoSymbol crypto, String link, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = hostedCheckoutRedirectValidateBeforeCall(pk, amount, crypto, link, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
