/*
 * CryptoGate API
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…`, or `sk_test_…` for sandbox). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package live.cryptogate.sdk.api;

import live.cryptogate.sdk.ApiException;
import live.cryptogate.sdk.model.CreateDetailedTransactionRequest;
import live.cryptogate.sdk.model.CreateTransactionRequest;
import live.cryptogate.sdk.model.CryptoSymbol;
import live.cryptogate.sdk.model.Error;
import live.cryptogate.sdk.model.InlineObject;
import live.cryptogate.sdk.model.ListTransactions200Response;
import live.cryptogate.sdk.model.TransactionEnvelope;
import live.cryptogate.sdk.model.TransactionStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TransactionsApi
 */
@Disabled
public class TransactionsApiTest {

    private final TransactionsApi api = new TransactionsApi();

    /**
     * Create an itemized transaction (Professional/Enterprise plans)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createDetailedTransactionTest() throws ApiException {
        CreateDetailedTransactionRequest createDetailedTransactionRequest = null;
        String xIdempotencyKey = null;
        TransactionEnvelope response = api.createDetailedTransaction(createDetailedTransactionRequest, xIdempotencyKey);
        // TODO: test validations
    }

    /**
     * Create a payment transaction
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTransactionTest() throws ApiException {
        CreateTransactionRequest createTransactionRequest = null;
        String xIdempotencyKey = null;
        TransactionEnvelope response = api.createTransaction(createTransactionRequest, xIdempotencyKey);
        // TODO: test validations
    }

    /**
     * Retrieve a single transaction
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTransactionTest() throws ApiException {
        String transactionId = null;
        TransactionEnvelope response = api.getTransaction(transactionId);
        // TODO: test validations
    }

    /**
     * List the merchant&#39;s transactions (newest first)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTransactionsTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        TransactionStatus status = null;
        CryptoSymbol crypto = null;
        ListTransactions200Response response = api.listTransactions(limit, offset, status, crypto);
        // TODO: test validations
    }

}
