/*
 * CryptoGate API
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package live.cryptogate.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import live.cryptogate.sdk.JSON;

/**
 * AccountLimits
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-27T17:50:21.664603656Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class AccountLimits {
  public static final String SERIALIZED_NAME_API_RATE_LIMIT_PER_MINUTE = "api_rate_limit_per_minute";
  @SerializedName(SERIALIZED_NAME_API_RATE_LIMIT_PER_MINUTE)
  @javax.annotation.Nullable
  private Integer apiRateLimitPerMinute;

  public static final String SERIALIZED_NAME_API_RATE_LIMIT_PER_HOUR = "api_rate_limit_per_hour";
  @SerializedName(SERIALIZED_NAME_API_RATE_LIMIT_PER_HOUR)
  @javax.annotation.Nullable
  private Integer apiRateLimitPerHour;

  public static final String SERIALIZED_NAME_WEBHOOK_SUPPORT = "webhook_support";
  @SerializedName(SERIALIZED_NAME_WEBHOOK_SUPPORT)
  @javax.annotation.Nullable
  private Boolean webhookSupport;

  public AccountLimits() {
  }

  public AccountLimits apiRateLimitPerMinute(@javax.annotation.Nullable Integer apiRateLimitPerMinute) {
    this.apiRateLimitPerMinute = apiRateLimitPerMinute;
    return this;
  }

  /**
   * Get apiRateLimitPerMinute
   * @return apiRateLimitPerMinute
   */
  @javax.annotation.Nullable
  public Integer getApiRateLimitPerMinute() {
    return apiRateLimitPerMinute;
  }

  public void setApiRateLimitPerMinute(@javax.annotation.Nullable Integer apiRateLimitPerMinute) {
    this.apiRateLimitPerMinute = apiRateLimitPerMinute;
  }


  public AccountLimits apiRateLimitPerHour(@javax.annotation.Nullable Integer apiRateLimitPerHour) {
    this.apiRateLimitPerHour = apiRateLimitPerHour;
    return this;
  }

  /**
   * Get apiRateLimitPerHour
   * @return apiRateLimitPerHour
   */
  @javax.annotation.Nullable
  public Integer getApiRateLimitPerHour() {
    return apiRateLimitPerHour;
  }

  public void setApiRateLimitPerHour(@javax.annotation.Nullable Integer apiRateLimitPerHour) {
    this.apiRateLimitPerHour = apiRateLimitPerHour;
  }


  public AccountLimits webhookSupport(@javax.annotation.Nullable Boolean webhookSupport) {
    this.webhookSupport = webhookSupport;
    return this;
  }

  /**
   * Get webhookSupport
   * @return webhookSupport
   */
  @javax.annotation.Nullable
  public Boolean getWebhookSupport() {
    return webhookSupport;
  }

  public void setWebhookSupport(@javax.annotation.Nullable Boolean webhookSupport) {
    this.webhookSupport = webhookSupport;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountLimits accountLimits = (AccountLimits) o;
    return Objects.equals(this.apiRateLimitPerMinute, accountLimits.apiRateLimitPerMinute) &&
        Objects.equals(this.apiRateLimitPerHour, accountLimits.apiRateLimitPerHour) &&
        Objects.equals(this.webhookSupport, accountLimits.webhookSupport);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiRateLimitPerMinute, apiRateLimitPerHour, webhookSupport);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountLimits {\n");
    sb.append("    apiRateLimitPerMinute: ").append(toIndentedString(apiRateLimitPerMinute)).append("\n");
    sb.append("    apiRateLimitPerHour: ").append(toIndentedString(apiRateLimitPerHour)).append("\n");
    sb.append("    webhookSupport: ").append(toIndentedString(webhookSupport)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("api_rate_limit_per_minute");
    openapiFields.add("api_rate_limit_per_hour");
    openapiFields.add("webhook_support");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AccountLimits
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AccountLimits.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AccountLimits is not found in the empty JSON string", AccountLimits.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AccountLimits.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AccountLimits` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AccountLimits.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AccountLimits' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AccountLimits> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AccountLimits.class));

       return (TypeAdapter<T>) new TypeAdapter<AccountLimits>() {
           @Override
           public void write(JsonWriter out, AccountLimits value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AccountLimits read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AccountLimits given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AccountLimits
   * @throws IOException if the JSON string is invalid with respect to AccountLimits
   */
  public static AccountLimits fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AccountLimits.class);
  }

  /**
   * Convert an instance of AccountLimits to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

