/*
 * CryptoGate API
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…`, or `sk_test_…` for sandbox). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package live.cryptogate.sdk.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Supported coin/token symbol. /cryptos/list is authoritative at runtime.
 */
@JsonAdapter(CryptoSymbol.Adapter.class)
public enum CryptoSymbol {
  
  BTC("BTC"),
  
  LTC("LTC"),
  
  DOGE("DOGE"),
  
  DASH("DASH"),
  
  ETH("ETH"),
  
  USDT("USDT"),
  
  USDC("USDC"),
  
  DAI("DAI"),
  
  WBTC("WBTC"),
  
  SHIB("SHIB"),
  
  PEPE("PEPE"),
  
  LINK("LINK"),
  
  UNI("UNI"),
  
  AAVE("AAVE"),
  
  MKR("MKR");

  private String value;

  CryptoSymbol(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CryptoSymbol fromValue(String value) {
    for (CryptoSymbol b : CryptoSymbol.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CryptoSymbol> {
    @Override
    public void write(final JsonWriter jsonWriter, final CryptoSymbol enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CryptoSymbol read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CryptoSymbol.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    CryptoSymbol.fromValue(value);
  }
}

