/*
 * CryptoGate API
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package live.cryptogate.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import live.cryptogate.sdk.JSON;

/**
 * GetPrices200ResponseData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-27T16:11:57.320760693Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class GetPrices200ResponseData {
  public static final String SERIALIZED_NAME_CRYPTO = "crypto";
  @SerializedName(SERIALIZED_NAME_CRYPTO)
  @javax.annotation.Nullable
  private Map<String, BigDecimal> crypto = new HashMap<>();

  public static final String SERIALIZED_NAME_FIAT = "fiat";
  @SerializedName(SERIALIZED_NAME_FIAT)
  @javax.annotation.Nullable
  private Map<String, BigDecimal> fiat = new HashMap<>();

  public static final String SERIALIZED_NAME_FETCHED_AT = "fetched_at";
  @SerializedName(SERIALIZED_NAME_FETCHED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime fetchedAt;

  public GetPrices200ResponseData() {
  }

  public GetPrices200ResponseData crypto(@javax.annotation.Nullable Map<String, BigDecimal> crypto) {
    this.crypto = crypto;
    return this;
  }

  public GetPrices200ResponseData putCryptoItem(String key, BigDecimal cryptoItem) {
    if (this.crypto == null) {
      this.crypto = new HashMap<>();
    }
    this.crypto.put(key, cryptoItem);
    return this;
  }

  /**
   * USD price per unit, keyed by crypto symbol (active coins only).
   * @return crypto
   */
  @javax.annotation.Nullable
  public Map<String, BigDecimal> getCrypto() {
    return crypto;
  }

  public void setCrypto(@javax.annotation.Nullable Map<String, BigDecimal> crypto) {
    this.crypto = crypto;
  }


  public GetPrices200ResponseData fiat(@javax.annotation.Nullable Map<String, BigDecimal> fiat) {
    this.fiat = fiat;
    return this;
  }

  public GetPrices200ResponseData putFiatItem(String key, BigDecimal fiatItem) {
    if (this.fiat == null) {
      this.fiat = new HashMap<>();
    }
    this.fiat.put(key, fiatItem);
    return this;
  }

  /**
   * USD value of one unit of each fiat currency.
   * @return fiat
   */
  @javax.annotation.Nullable
  public Map<String, BigDecimal> getFiat() {
    return fiat;
  }

  public void setFiat(@javax.annotation.Nullable Map<String, BigDecimal> fiat) {
    this.fiat = fiat;
  }


  public GetPrices200ResponseData fetchedAt(@javax.annotation.Nullable OffsetDateTime fetchedAt) {
    this.fetchedAt = fetchedAt;
    return this;
  }

  /**
   * Get fetchedAt
   * @return fetchedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getFetchedAt() {
    return fetchedAt;
  }

  public void setFetchedAt(@javax.annotation.Nullable OffsetDateTime fetchedAt) {
    this.fetchedAt = fetchedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPrices200ResponseData getPrices200ResponseData = (GetPrices200ResponseData) o;
    return Objects.equals(this.crypto, getPrices200ResponseData.crypto) &&
        Objects.equals(this.fiat, getPrices200ResponseData.fiat) &&
        Objects.equals(this.fetchedAt, getPrices200ResponseData.fetchedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(crypto, fiat, fetchedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPrices200ResponseData {\n");
    sb.append("    crypto: ").append(toIndentedString(crypto)).append("\n");
    sb.append("    fiat: ").append(toIndentedString(fiat)).append("\n");
    sb.append("    fetchedAt: ").append(toIndentedString(fetchedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("crypto");
    openapiFields.add("fiat");
    openapiFields.add("fetched_at");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetPrices200ResponseData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetPrices200ResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetPrices200ResponseData is not found in the empty JSON string", GetPrices200ResponseData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetPrices200ResponseData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetPrices200ResponseData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetPrices200ResponseData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetPrices200ResponseData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetPrices200ResponseData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetPrices200ResponseData.class));

       return (TypeAdapter<T>) new TypeAdapter<GetPrices200ResponseData>() {
           @Override
           public void write(JsonWriter out, GetPrices200ResponseData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetPrices200ResponseData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetPrices200ResponseData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetPrices200ResponseData
   * @throws IOException if the JSON string is invalid with respect to GetPrices200ResponseData
   */
  public static GetPrices200ResponseData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetPrices200ResponseData.class);
  }

  /**
   * Convert an instance of GetPrices200ResponseData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

