/*
 * CryptoGate API
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package live.cryptogate.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import live.cryptogate.sdk.JSON;

/**
 * GetStats200ResponseData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-27T16:11:57.320760693Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class GetStats200ResponseData {
  public static final String SERIALIZED_NAME_TOTAL_TRANSACTIONS = "total_transactions";
  @SerializedName(SERIALIZED_NAME_TOTAL_TRANSACTIONS)
  @javax.annotation.Nullable
  private Integer totalTransactions;

  public static final String SERIALIZED_NAME_MONTHLY_TRANSACTIONS = "monthly_transactions";
  @SerializedName(SERIALIZED_NAME_MONTHLY_TRANSACTIONS)
  @javax.annotation.Nullable
  private Integer monthlyTransactions;

  public static final String SERIALIZED_NAME_TOTAL_VOLUME_FIAT = "total_volume_fiat";
  @SerializedName(SERIALIZED_NAME_TOTAL_VOLUME_FIAT)
  @javax.annotation.Nullable
  private BigDecimal totalVolumeFiat;

  public static final String SERIALIZED_NAME_UNIQUE_CUSTOMERS = "unique_customers";
  @SerializedName(SERIALIZED_NAME_UNIQUE_CUSTOMERS)
  @javax.annotation.Nullable
  private Integer uniqueCustomers;

  public GetStats200ResponseData() {
  }

  public GetStats200ResponseData totalTransactions(@javax.annotation.Nullable Integer totalTransactions) {
    this.totalTransactions = totalTransactions;
    return this;
  }

  /**
   * Get totalTransactions
   * @return totalTransactions
   */
  @javax.annotation.Nullable
  public Integer getTotalTransactions() {
    return totalTransactions;
  }

  public void setTotalTransactions(@javax.annotation.Nullable Integer totalTransactions) {
    this.totalTransactions = totalTransactions;
  }


  public GetStats200ResponseData monthlyTransactions(@javax.annotation.Nullable Integer monthlyTransactions) {
    this.monthlyTransactions = monthlyTransactions;
    return this;
  }

  /**
   * Get monthlyTransactions
   * @return monthlyTransactions
   */
  @javax.annotation.Nullable
  public Integer getMonthlyTransactions() {
    return monthlyTransactions;
  }

  public void setMonthlyTransactions(@javax.annotation.Nullable Integer monthlyTransactions) {
    this.monthlyTransactions = monthlyTransactions;
  }


  public GetStats200ResponseData totalVolumeFiat(@javax.annotation.Nullable BigDecimal totalVolumeFiat) {
    this.totalVolumeFiat = totalVolumeFiat;
    return this;
  }

  /**
   * Get totalVolumeFiat
   * @return totalVolumeFiat
   */
  @javax.annotation.Nullable
  public BigDecimal getTotalVolumeFiat() {
    return totalVolumeFiat;
  }

  public void setTotalVolumeFiat(@javax.annotation.Nullable BigDecimal totalVolumeFiat) {
    this.totalVolumeFiat = totalVolumeFiat;
  }


  public GetStats200ResponseData uniqueCustomers(@javax.annotation.Nullable Integer uniqueCustomers) {
    this.uniqueCustomers = uniqueCustomers;
    return this;
  }

  /**
   * Get uniqueCustomers
   * @return uniqueCustomers
   */
  @javax.annotation.Nullable
  public Integer getUniqueCustomers() {
    return uniqueCustomers;
  }

  public void setUniqueCustomers(@javax.annotation.Nullable Integer uniqueCustomers) {
    this.uniqueCustomers = uniqueCustomers;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetStats200ResponseData getStats200ResponseData = (GetStats200ResponseData) o;
    return Objects.equals(this.totalTransactions, getStats200ResponseData.totalTransactions) &&
        Objects.equals(this.monthlyTransactions, getStats200ResponseData.monthlyTransactions) &&
        Objects.equals(this.totalVolumeFiat, getStats200ResponseData.totalVolumeFiat) &&
        Objects.equals(this.uniqueCustomers, getStats200ResponseData.uniqueCustomers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalTransactions, monthlyTransactions, totalVolumeFiat, uniqueCustomers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetStats200ResponseData {\n");
    sb.append("    totalTransactions: ").append(toIndentedString(totalTransactions)).append("\n");
    sb.append("    monthlyTransactions: ").append(toIndentedString(monthlyTransactions)).append("\n");
    sb.append("    totalVolumeFiat: ").append(toIndentedString(totalVolumeFiat)).append("\n");
    sb.append("    uniqueCustomers: ").append(toIndentedString(uniqueCustomers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("total_transactions");
    openapiFields.add("monthly_transactions");
    openapiFields.add("total_volume_fiat");
    openapiFields.add("unique_customers");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetStats200ResponseData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetStats200ResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetStats200ResponseData is not found in the empty JSON string", GetStats200ResponseData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetStats200ResponseData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetStats200ResponseData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetStats200ResponseData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetStats200ResponseData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetStats200ResponseData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetStats200ResponseData.class));

       return (TypeAdapter<T>) new TypeAdapter<GetStats200ResponseData>() {
           @Override
           public void write(JsonWriter out, GetStats200ResponseData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetStats200ResponseData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetStats200ResponseData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetStats200ResponseData
   * @throws IOException if the JSON string is invalid with respect to GetStats200ResponseData
   */
  public static GetStats200ResponseData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetStats200ResponseData.class);
  }

  /**
   * Convert an instance of GetStats200ResponseData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

