/*
 * CryptoGate API
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package live.cryptogate.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import live.cryptogate.sdk.model.Cryptocurrency;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import live.cryptogate.sdk.JSON;

/**
 * ListCryptocurrencies200ResponseData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-27T17:50:21.664603656Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class ListCryptocurrencies200ResponseData {
  public static final String SERIALIZED_NAME_CRYPTOCURRENCIES = "cryptocurrencies";
  @SerializedName(SERIALIZED_NAME_CRYPTOCURRENCIES)
  @javax.annotation.Nullable
  private List<Cryptocurrency> cryptocurrencies = new ArrayList<>();

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  @javax.annotation.Nullable
  private Integer total;

  public ListCryptocurrencies200ResponseData() {
  }

  public ListCryptocurrencies200ResponseData cryptocurrencies(@javax.annotation.Nullable List<Cryptocurrency> cryptocurrencies) {
    this.cryptocurrencies = cryptocurrencies;
    return this;
  }

  public ListCryptocurrencies200ResponseData addCryptocurrenciesItem(Cryptocurrency cryptocurrenciesItem) {
    if (this.cryptocurrencies == null) {
      this.cryptocurrencies = new ArrayList<>();
    }
    this.cryptocurrencies.add(cryptocurrenciesItem);
    return this;
  }

  /**
   * Get cryptocurrencies
   * @return cryptocurrencies
   */
  @javax.annotation.Nullable
  public List<Cryptocurrency> getCryptocurrencies() {
    return cryptocurrencies;
  }

  public void setCryptocurrencies(@javax.annotation.Nullable List<Cryptocurrency> cryptocurrencies) {
    this.cryptocurrencies = cryptocurrencies;
  }


  public ListCryptocurrencies200ResponseData total(@javax.annotation.Nullable Integer total) {
    this.total = total;
    return this;
  }

  /**
   * Get total
   * @return total
   */
  @javax.annotation.Nullable
  public Integer getTotal() {
    return total;
  }

  public void setTotal(@javax.annotation.Nullable Integer total) {
    this.total = total;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListCryptocurrencies200ResponseData listCryptocurrencies200ResponseData = (ListCryptocurrencies200ResponseData) o;
    return Objects.equals(this.cryptocurrencies, listCryptocurrencies200ResponseData.cryptocurrencies) &&
        Objects.equals(this.total, listCryptocurrencies200ResponseData.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cryptocurrencies, total);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListCryptocurrencies200ResponseData {\n");
    sb.append("    cryptocurrencies: ").append(toIndentedString(cryptocurrencies)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cryptocurrencies");
    openapiFields.add("total");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ListCryptocurrencies200ResponseData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ListCryptocurrencies200ResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ListCryptocurrencies200ResponseData is not found in the empty JSON string", ListCryptocurrencies200ResponseData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ListCryptocurrencies200ResponseData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ListCryptocurrencies200ResponseData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("cryptocurrencies") != null && !jsonObj.get("cryptocurrencies").isJsonNull()) {
        JsonArray jsonArraycryptocurrencies = jsonObj.getAsJsonArray("cryptocurrencies");
        if (jsonArraycryptocurrencies != null) {
          // ensure the json data is an array
          if (!jsonObj.get("cryptocurrencies").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `cryptocurrencies` to be an array in the JSON string but got `%s`", jsonObj.get("cryptocurrencies").toString()));
          }

          // validate the optional field `cryptocurrencies` (array)
          for (int i = 0; i < jsonArraycryptocurrencies.size(); i++) {
            Cryptocurrency.validateJsonElement(jsonArraycryptocurrencies.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListCryptocurrencies200ResponseData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListCryptocurrencies200ResponseData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListCryptocurrencies200ResponseData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListCryptocurrencies200ResponseData.class));

       return (TypeAdapter<T>) new TypeAdapter<ListCryptocurrencies200ResponseData>() {
           @Override
           public void write(JsonWriter out, ListCryptocurrencies200ResponseData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ListCryptocurrencies200ResponseData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ListCryptocurrencies200ResponseData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ListCryptocurrencies200ResponseData
   * @throws IOException if the JSON string is invalid with respect to ListCryptocurrencies200ResponseData
   */
  public static ListCryptocurrencies200ResponseData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListCryptocurrencies200ResponseData.class);
  }

  /**
   * Convert an instance of ListCryptocurrencies200ResponseData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

