/*
 * CryptoGate API
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package live.cryptogate.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import live.cryptogate.sdk.JSON;

/**
 * One on-chain payment toward the transaction.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-27T16:11:57.320760693Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class PaymentSplit {
  public static final String SERIALIZED_NAME_TXID = "txid";
  @SerializedName(SERIALIZED_NAME_TXID)
  @javax.annotation.Nullable
  private String txid;

  public static final String SERIALIZED_NAME_AMOUNT_CRYPTO = "amount_crypto";
  @SerializedName(SERIALIZED_NAME_AMOUNT_CRYPTO)
  @javax.annotation.Nullable
  private BigDecimal amountCrypto;

  public static final String SERIALIZED_NAME_CONFIRMATIONS = "confirmations";
  @SerializedName(SERIALIZED_NAME_CONFIRMATIONS)
  @javax.annotation.Nullable
  private Integer confirmations;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private String status;

  public static final String SERIALIZED_NAME_DETECTED_AT = "detected_at";
  @SerializedName(SERIALIZED_NAME_DETECTED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime detectedAt;

  public static final String SERIALIZED_NAME_CONFIRMED_AT = "confirmed_at";
  @SerializedName(SERIALIZED_NAME_CONFIRMED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime confirmedAt;

  public PaymentSplit() {
  }

  public PaymentSplit txid(@javax.annotation.Nullable String txid) {
    this.txid = txid;
    return this;
  }

  /**
   * On-chain transaction hash (blockchain id, NOT the CryptoGate transaction_id).
   * @return txid
   */
  @javax.annotation.Nullable
  public String getTxid() {
    return txid;
  }

  public void setTxid(@javax.annotation.Nullable String txid) {
    this.txid = txid;
  }


  public PaymentSplit amountCrypto(@javax.annotation.Nullable BigDecimal amountCrypto) {
    this.amountCrypto = amountCrypto;
    return this;
  }

  /**
   * Get amountCrypto
   * @return amountCrypto
   */
  @javax.annotation.Nullable
  public BigDecimal getAmountCrypto() {
    return amountCrypto;
  }

  public void setAmountCrypto(@javax.annotation.Nullable BigDecimal amountCrypto) {
    this.amountCrypto = amountCrypto;
  }


  public PaymentSplit confirmations(@javax.annotation.Nullable Integer confirmations) {
    this.confirmations = confirmations;
    return this;
  }

  /**
   * Get confirmations
   * @return confirmations
   */
  @javax.annotation.Nullable
  public Integer getConfirmations() {
    return confirmations;
  }

  public void setConfirmations(@javax.annotation.Nullable Integer confirmations) {
    this.confirmations = confirmations;
  }


  public PaymentSplit status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public PaymentSplit detectedAt(@javax.annotation.Nullable OffsetDateTime detectedAt) {
    this.detectedAt = detectedAt;
    return this;
  }

  /**
   * Get detectedAt
   * @return detectedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDetectedAt() {
    return detectedAt;
  }

  public void setDetectedAt(@javax.annotation.Nullable OffsetDateTime detectedAt) {
    this.detectedAt = detectedAt;
  }


  public PaymentSplit confirmedAt(@javax.annotation.Nullable OffsetDateTime confirmedAt) {
    this.confirmedAt = confirmedAt;
    return this;
  }

  /**
   * Get confirmedAt
   * @return confirmedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getConfirmedAt() {
    return confirmedAt;
  }

  public void setConfirmedAt(@javax.annotation.Nullable OffsetDateTime confirmedAt) {
    this.confirmedAt = confirmedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentSplit paymentSplit = (PaymentSplit) o;
    return Objects.equals(this.txid, paymentSplit.txid) &&
        Objects.equals(this.amountCrypto, paymentSplit.amountCrypto) &&
        Objects.equals(this.confirmations, paymentSplit.confirmations) &&
        Objects.equals(this.status, paymentSplit.status) &&
        Objects.equals(this.detectedAt, paymentSplit.detectedAt) &&
        Objects.equals(this.confirmedAt, paymentSplit.confirmedAt);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(txid, amountCrypto, confirmations, status, detectedAt, confirmedAt);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentSplit {\n");
    sb.append("    txid: ").append(toIndentedString(txid)).append("\n");
    sb.append("    amountCrypto: ").append(toIndentedString(amountCrypto)).append("\n");
    sb.append("    confirmations: ").append(toIndentedString(confirmations)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    detectedAt: ").append(toIndentedString(detectedAt)).append("\n");
    sb.append("    confirmedAt: ").append(toIndentedString(confirmedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("txid");
    openapiFields.add("amount_crypto");
    openapiFields.add("confirmations");
    openapiFields.add("status");
    openapiFields.add("detected_at");
    openapiFields.add("confirmed_at");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PaymentSplit
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PaymentSplit.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PaymentSplit is not found in the empty JSON string", PaymentSplit.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PaymentSplit.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PaymentSplit` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("txid") != null && !jsonObj.get("txid").isJsonNull()) && !jsonObj.get("txid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `txid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("txid").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PaymentSplit.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PaymentSplit' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PaymentSplit> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PaymentSplit.class));

       return (TypeAdapter<T>) new TypeAdapter<PaymentSplit>() {
           @Override
           public void write(JsonWriter out, PaymentSplit value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PaymentSplit read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PaymentSplit given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PaymentSplit
   * @throws IOException if the JSON string is invalid with respect to PaymentSplit
   */
  public static PaymentSplit fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PaymentSplit.class);
  }

  /**
   * Convert an instance of PaymentSplit to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

