/*
 * CryptoGate API
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package live.cryptogate.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import live.cryptogate.sdk.model.CryptoSymbol;
import live.cryptogate.sdk.model.FiatCurrency;
import live.cryptogate.sdk.model.LineItem;
import live.cryptogate.sdk.model.PaymentSplit;
import live.cryptogate.sdk.model.TransactionStatus;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import live.cryptogate.sdk.JSON;

/**
 * The canonical, curated public view of a transaction (same shape from create, get and list). Internal fields (capability tokens, client_ip, address_index, derivation/db internals) are deliberately NOT exposed. 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-27T17:50:21.664603656Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class Transaction {
  public static final String SERIALIZED_NAME_TRANSACTION_ID = "transaction_id";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_ID)
  @javax.annotation.Nonnull
  private String transactionId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private TransactionStatus status;

  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    BASIC("basic"),
    
    DETAILED("detailed");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nullable
  private TypeEnum type;

  public static final String SERIALIZED_NAME_CRYPTO = "crypto";
  @SerializedName(SERIALIZED_NAME_CRYPTO)
  @javax.annotation.Nonnull
  private CryptoSymbol crypto;

  public static final String SERIALIZED_NAME_DEPOSIT_ADDRESS = "deposit_address";
  @SerializedName(SERIALIZED_NAME_DEPOSIT_ADDRESS)
  @javax.annotation.Nullable
  private String depositAddress;

  public static final String SERIALIZED_NAME_AMOUNT_CRYPTO = "amount_crypto";
  @SerializedName(SERIALIZED_NAME_AMOUNT_CRYPTO)
  @javax.annotation.Nullable
  private BigDecimal amountCrypto;

  public static final String SERIALIZED_NAME_AMOUNT_FIAT = "amount_fiat";
  @SerializedName(SERIALIZED_NAME_AMOUNT_FIAT)
  @javax.annotation.Nonnull
  private BigDecimal amountFiat;

  public static final String SERIALIZED_NAME_AMOUNT_USD = "amount_usd";
  @SerializedName(SERIALIZED_NAME_AMOUNT_USD)
  @javax.annotation.Nonnull
  private BigDecimal amountUsd;

  public static final String SERIALIZED_NAME_AMOUNT_PAID = "amount_paid";
  @SerializedName(SERIALIZED_NAME_AMOUNT_PAID)
  @javax.annotation.Nullable
  private BigDecimal amountPaid;

  public static final String SERIALIZED_NAME_AMOUNT_REMAINING = "amount_remaining";
  @SerializedName(SERIALIZED_NAME_AMOUNT_REMAINING)
  @javax.annotation.Nullable
  private BigDecimal amountRemaining;

  public static final String SERIALIZED_NAME_CURRENCY_FIAT = "currency_fiat";
  @SerializedName(SERIALIZED_NAME_CURRENCY_FIAT)
  @javax.annotation.Nonnull
  private FiatCurrency currencyFiat = FiatCurrency.USD;

  public static final String SERIALIZED_NAME_FIAT_TO_USD_RATE = "fiat_to_usd_rate";
  @SerializedName(SERIALIZED_NAME_FIAT_TO_USD_RATE)
  @javax.annotation.Nullable
  private BigDecimal fiatToUsdRate;

  public static final String SERIALIZED_NAME_EXCHANGE_RATE = "exchange_rate";
  @SerializedName(SERIALIZED_NAME_EXCHANGE_RATE)
  @javax.annotation.Nullable
  private BigDecimal exchangeRate;

  public static final String SERIALIZED_NAME_CONFIRMATIONS_REQUIRED = "confirmations_required";
  @SerializedName(SERIALIZED_NAME_CONFIRMATIONS_REQUIRED)
  @javax.annotation.Nullable
  private Integer confirmationsRequired;

  public static final String SERIALIZED_NAME_PAYMENT_URL = "payment_url";
  @SerializedName(SERIALIZED_NAME_PAYMENT_URL)
  @javax.annotation.Nullable
  private URI paymentUrl;

  public static final String SERIALIZED_NAME_ORDER_ID = "order_id";
  @SerializedName(SERIALIZED_NAME_ORDER_ID)
  @javax.annotation.Nullable
  private String orderId;

  public static final String SERIALIZED_NAME_CUSTOMER_EMAIL = "customer_email";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_EMAIL)
  @javax.annotation.Nullable
  private String customerEmail;

  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  @javax.annotation.Nullable
  private List<LineItem> items;

  public static final String SERIALIZED_NAME_PAYMENTS = "payments";
  @SerializedName(SERIALIZED_NAME_PAYMENTS)
  @javax.annotation.Nullable
  private List<PaymentSplit> payments = new ArrayList<>();

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  @javax.annotation.Nullable
  private Map<String, String> metadata = new HashMap<>();

  public static final String SERIALIZED_NAME_SUCCESS_URL = "success_url";
  @SerializedName(SERIALIZED_NAME_SUCCESS_URL)
  @javax.annotation.Nullable
  private String successUrl;

  public static final String SERIALIZED_NAME_CANCEL_URL = "cancel_url";
  @SerializedName(SERIALIZED_NAME_CANCEL_URL)
  @javax.annotation.Nullable
  private String cancelUrl;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_EXPIRES_AT = "expires_at";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime expiresAt;

  public Transaction() {
  }

  public Transaction transactionId(@javax.annotation.Nonnull String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

  /**
   * Get transactionId
   * @return transactionId
   */
  @javax.annotation.Nonnull
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(@javax.annotation.Nonnull String transactionId) {
    this.transactionId = transactionId;
  }


  public Transaction status(@javax.annotation.Nonnull TransactionStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public TransactionStatus getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull TransactionStatus status) {
    this.status = status;
  }


  public Transaction type(@javax.annotation.Nullable TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  public TypeEnum getType() {
    return type;
  }

  public void setType(@javax.annotation.Nullable TypeEnum type) {
    this.type = type;
  }


  public Transaction crypto(@javax.annotation.Nonnull CryptoSymbol crypto) {
    this.crypto = crypto;
    return this;
  }

  /**
   * Get crypto
   * @return crypto
   */
  @javax.annotation.Nonnull
  public CryptoSymbol getCrypto() {
    return crypto;
  }

  public void setCrypto(@javax.annotation.Nonnull CryptoSymbol crypto) {
    this.crypto = crypto;
  }


  public Transaction depositAddress(@javax.annotation.Nullable String depositAddress) {
    this.depositAddress = depositAddress;
    return this;
  }

  /**
   * Get depositAddress
   * @return depositAddress
   */
  @javax.annotation.Nullable
  public String getDepositAddress() {
    return depositAddress;
  }

  public void setDepositAddress(@javax.annotation.Nullable String depositAddress) {
    this.depositAddress = depositAddress;
  }


  public Transaction amountCrypto(@javax.annotation.Nullable BigDecimal amountCrypto) {
    this.amountCrypto = amountCrypto;
    return this;
  }

  /**
   * Get amountCrypto
   * @return amountCrypto
   */
  @javax.annotation.Nullable
  public BigDecimal getAmountCrypto() {
    return amountCrypto;
  }

  public void setAmountCrypto(@javax.annotation.Nullable BigDecimal amountCrypto) {
    this.amountCrypto = amountCrypto;
  }


  public Transaction amountFiat(@javax.annotation.Nonnull BigDecimal amountFiat) {
    this.amountFiat = amountFiat;
    return this;
  }

  /**
   * Get amountFiat
   * @return amountFiat
   */
  @javax.annotation.Nonnull
  public BigDecimal getAmountFiat() {
    return amountFiat;
  }

  public void setAmountFiat(@javax.annotation.Nonnull BigDecimal amountFiat) {
    this.amountFiat = amountFiat;
  }


  public Transaction amountUsd(@javax.annotation.Nonnull BigDecimal amountUsd) {
    this.amountUsd = amountUsd;
    return this;
  }

  /**
   * Get amountUsd
   * @return amountUsd
   */
  @javax.annotation.Nonnull
  public BigDecimal getAmountUsd() {
    return amountUsd;
  }

  public void setAmountUsd(@javax.annotation.Nonnull BigDecimal amountUsd) {
    this.amountUsd = amountUsd;
  }


  public Transaction amountPaid(@javax.annotation.Nullable BigDecimal amountPaid) {
    this.amountPaid = amountPaid;
    return this;
  }

  /**
   * Get amountPaid
   * @return amountPaid
   */
  @javax.annotation.Nullable
  public BigDecimal getAmountPaid() {
    return amountPaid;
  }

  public void setAmountPaid(@javax.annotation.Nullable BigDecimal amountPaid) {
    this.amountPaid = amountPaid;
  }


  public Transaction amountRemaining(@javax.annotation.Nullable BigDecimal amountRemaining) {
    this.amountRemaining = amountRemaining;
    return this;
  }

  /**
   * Get amountRemaining
   * @return amountRemaining
   */
  @javax.annotation.Nullable
  public BigDecimal getAmountRemaining() {
    return amountRemaining;
  }

  public void setAmountRemaining(@javax.annotation.Nullable BigDecimal amountRemaining) {
    this.amountRemaining = amountRemaining;
  }


  public Transaction currencyFiat(@javax.annotation.Nonnull FiatCurrency currencyFiat) {
    this.currencyFiat = currencyFiat;
    return this;
  }

  /**
   * Get currencyFiat
   * @return currencyFiat
   */
  @javax.annotation.Nonnull
  public FiatCurrency getCurrencyFiat() {
    return currencyFiat;
  }

  public void setCurrencyFiat(@javax.annotation.Nonnull FiatCurrency currencyFiat) {
    this.currencyFiat = currencyFiat;
  }


  public Transaction fiatToUsdRate(@javax.annotation.Nullable BigDecimal fiatToUsdRate) {
    this.fiatToUsdRate = fiatToUsdRate;
    return this;
  }

  /**
   * Get fiatToUsdRate
   * @return fiatToUsdRate
   */
  @javax.annotation.Nullable
  public BigDecimal getFiatToUsdRate() {
    return fiatToUsdRate;
  }

  public void setFiatToUsdRate(@javax.annotation.Nullable BigDecimal fiatToUsdRate) {
    this.fiatToUsdRate = fiatToUsdRate;
  }


  public Transaction exchangeRate(@javax.annotation.Nullable BigDecimal exchangeRate) {
    this.exchangeRate = exchangeRate;
    return this;
  }

  /**
   * USD per unit of crypto, locked at creation.
   * @return exchangeRate
   */
  @javax.annotation.Nullable
  public BigDecimal getExchangeRate() {
    return exchangeRate;
  }

  public void setExchangeRate(@javax.annotation.Nullable BigDecimal exchangeRate) {
    this.exchangeRate = exchangeRate;
  }


  public Transaction confirmationsRequired(@javax.annotation.Nullable Integer confirmationsRequired) {
    this.confirmationsRequired = confirmationsRequired;
    return this;
  }

  /**
   * Get confirmationsRequired
   * @return confirmationsRequired
   */
  @javax.annotation.Nullable
  public Integer getConfirmationsRequired() {
    return confirmationsRequired;
  }

  public void setConfirmationsRequired(@javax.annotation.Nullable Integer confirmationsRequired) {
    this.confirmationsRequired = confirmationsRequired;
  }


  public Transaction paymentUrl(@javax.annotation.Nullable URI paymentUrl) {
    this.paymentUrl = paymentUrl;
    return this;
  }

  /**
   * Get paymentUrl
   * @return paymentUrl
   */
  @javax.annotation.Nullable
  public URI getPaymentUrl() {
    return paymentUrl;
  }

  public void setPaymentUrl(@javax.annotation.Nullable URI paymentUrl) {
    this.paymentUrl = paymentUrl;
  }


  public Transaction orderId(@javax.annotation.Nullable String orderId) {
    this.orderId = orderId;
    return this;
  }

  /**
   * Get orderId
   * @return orderId
   */
  @javax.annotation.Nullable
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(@javax.annotation.Nullable String orderId) {
    this.orderId = orderId;
  }


  public Transaction customerEmail(@javax.annotation.Nullable String customerEmail) {
    this.customerEmail = customerEmail;
    return this;
  }

  /**
   * Get customerEmail
   * @return customerEmail
   */
  @javax.annotation.Nullable
  public String getCustomerEmail() {
    return customerEmail;
  }

  public void setCustomerEmail(@javax.annotation.Nullable String customerEmail) {
    this.customerEmail = customerEmail;
  }


  public Transaction items(@javax.annotation.Nullable List<LineItem> items) {
    this.items = items;
    return this;
  }

  public Transaction addItemsItem(LineItem itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * Get items
   * @return items
   */
  @javax.annotation.Nullable
  public List<LineItem> getItems() {
    return items;
  }

  public void setItems(@javax.annotation.Nullable List<LineItem> items) {
    this.items = items;
  }


  public Transaction payments(@javax.annotation.Nullable List<PaymentSplit> payments) {
    this.payments = payments;
    return this;
  }

  public Transaction addPaymentsItem(PaymentSplit paymentsItem) {
    if (this.payments == null) {
      this.payments = new ArrayList<>();
    }
    this.payments.add(paymentsItem);
    return this;
  }

  /**
   * On-chain payments detected toward this transaction.
   * @return payments
   */
  @javax.annotation.Nullable
  public List<PaymentSplit> getPayments() {
    return payments;
  }

  public void setPayments(@javax.annotation.Nullable List<PaymentSplit> payments) {
    this.payments = payments;
  }


  public Transaction metadata(@javax.annotation.Nullable Map<String, String> metadata) {
    this.metadata = metadata;
    return this;
  }

  public Transaction putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).
   * @return metadata
   */
  @javax.annotation.Nullable
  public Map<String, String> getMetadata() {
    return metadata;
  }

  public void setMetadata(@javax.annotation.Nullable Map<String, String> metadata) {
    this.metadata = metadata;
  }


  public Transaction successUrl(@javax.annotation.Nullable String successUrl) {
    this.successUrl = successUrl;
    return this;
  }

  /**
   * Get successUrl
   * @return successUrl
   */
  @javax.annotation.Nullable
  public String getSuccessUrl() {
    return successUrl;
  }

  public void setSuccessUrl(@javax.annotation.Nullable String successUrl) {
    this.successUrl = successUrl;
  }


  public Transaction cancelUrl(@javax.annotation.Nullable String cancelUrl) {
    this.cancelUrl = cancelUrl;
    return this;
  }

  /**
   * Get cancelUrl
   * @return cancelUrl
   */
  @javax.annotation.Nullable
  public String getCancelUrl() {
    return cancelUrl;
  }

  public void setCancelUrl(@javax.annotation.Nullable String cancelUrl) {
    this.cancelUrl = cancelUrl;
  }


  public Transaction createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public Transaction updatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public Transaction expiresAt(@javax.annotation.Nonnull OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(@javax.annotation.Nonnull OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transaction transaction = (Transaction) o;
    return Objects.equals(this.transactionId, transaction.transactionId) &&
        Objects.equals(this.status, transaction.status) &&
        Objects.equals(this.type, transaction.type) &&
        Objects.equals(this.crypto, transaction.crypto) &&
        Objects.equals(this.depositAddress, transaction.depositAddress) &&
        Objects.equals(this.amountCrypto, transaction.amountCrypto) &&
        Objects.equals(this.amountFiat, transaction.amountFiat) &&
        Objects.equals(this.amountUsd, transaction.amountUsd) &&
        Objects.equals(this.amountPaid, transaction.amountPaid) &&
        Objects.equals(this.amountRemaining, transaction.amountRemaining) &&
        Objects.equals(this.currencyFiat, transaction.currencyFiat) &&
        Objects.equals(this.fiatToUsdRate, transaction.fiatToUsdRate) &&
        Objects.equals(this.exchangeRate, transaction.exchangeRate) &&
        Objects.equals(this.confirmationsRequired, transaction.confirmationsRequired) &&
        Objects.equals(this.paymentUrl, transaction.paymentUrl) &&
        Objects.equals(this.orderId, transaction.orderId) &&
        Objects.equals(this.customerEmail, transaction.customerEmail) &&
        Objects.equals(this.items, transaction.items) &&
        Objects.equals(this.payments, transaction.payments) &&
        Objects.equals(this.metadata, transaction.metadata) &&
        Objects.equals(this.successUrl, transaction.successUrl) &&
        Objects.equals(this.cancelUrl, transaction.cancelUrl) &&
        Objects.equals(this.createdAt, transaction.createdAt) &&
        Objects.equals(this.updatedAt, transaction.updatedAt) &&
        Objects.equals(this.expiresAt, transaction.expiresAt);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionId, status, type, crypto, depositAddress, amountCrypto, amountFiat, amountUsd, amountPaid, amountRemaining, currencyFiat, fiatToUsdRate, exchangeRate, confirmationsRequired, paymentUrl, orderId, customerEmail, items, payments, metadata, successUrl, cancelUrl, createdAt, updatedAt, expiresAt);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transaction {\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    crypto: ").append(toIndentedString(crypto)).append("\n");
    sb.append("    depositAddress: ").append(toIndentedString(depositAddress)).append("\n");
    sb.append("    amountCrypto: ").append(toIndentedString(amountCrypto)).append("\n");
    sb.append("    amountFiat: ").append(toIndentedString(amountFiat)).append("\n");
    sb.append("    amountUsd: ").append(toIndentedString(amountUsd)).append("\n");
    sb.append("    amountPaid: ").append(toIndentedString(amountPaid)).append("\n");
    sb.append("    amountRemaining: ").append(toIndentedString(amountRemaining)).append("\n");
    sb.append("    currencyFiat: ").append(toIndentedString(currencyFiat)).append("\n");
    sb.append("    fiatToUsdRate: ").append(toIndentedString(fiatToUsdRate)).append("\n");
    sb.append("    exchangeRate: ").append(toIndentedString(exchangeRate)).append("\n");
    sb.append("    confirmationsRequired: ").append(toIndentedString(confirmationsRequired)).append("\n");
    sb.append("    paymentUrl: ").append(toIndentedString(paymentUrl)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    customerEmail: ").append(toIndentedString(customerEmail)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    payments: ").append(toIndentedString(payments)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    successUrl: ").append(toIndentedString(successUrl)).append("\n");
    sb.append("    cancelUrl: ").append(toIndentedString(cancelUrl)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("transaction_id");
    openapiFields.add("status");
    openapiFields.add("type");
    openapiFields.add("crypto");
    openapiFields.add("deposit_address");
    openapiFields.add("amount_crypto");
    openapiFields.add("amount_fiat");
    openapiFields.add("amount_usd");
    openapiFields.add("amount_paid");
    openapiFields.add("amount_remaining");
    openapiFields.add("currency_fiat");
    openapiFields.add("fiat_to_usd_rate");
    openapiFields.add("exchange_rate");
    openapiFields.add("confirmations_required");
    openapiFields.add("payment_url");
    openapiFields.add("order_id");
    openapiFields.add("customer_email");
    openapiFields.add("items");
    openapiFields.add("payments");
    openapiFields.add("metadata");
    openapiFields.add("success_url");
    openapiFields.add("cancel_url");
    openapiFields.add("created_at");
    openapiFields.add("updated_at");
    openapiFields.add("expires_at");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("transaction_id");
    openapiRequiredFields.add("status");
    openapiRequiredFields.add("crypto");
    openapiRequiredFields.add("amount_fiat");
    openapiRequiredFields.add("amount_usd");
    openapiRequiredFields.add("currency_fiat");
    openapiRequiredFields.add("created_at");
    openapiRequiredFields.add("expires_at");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Transaction
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Transaction.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Transaction is not found in the empty JSON string", Transaction.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Transaction.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Transaction` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Transaction.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("transaction_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `transaction_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transaction_id").toString()));
      }
      // validate the required field `status`
      TransactionStatus.validateJsonElement(jsonObj.get("status"));
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      // validate the optional field `type`
      if (jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) {
        TypeEnum.validateJsonElement(jsonObj.get("type"));
      }
      // validate the required field `crypto`
      CryptoSymbol.validateJsonElement(jsonObj.get("crypto"));
      if ((jsonObj.get("deposit_address") != null && !jsonObj.get("deposit_address").isJsonNull()) && !jsonObj.get("deposit_address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `deposit_address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("deposit_address").toString()));
      }
      // validate the required field `currency_fiat`
      FiatCurrency.validateJsonElement(jsonObj.get("currency_fiat"));
      if ((jsonObj.get("payment_url") != null && !jsonObj.get("payment_url").isJsonNull()) && !jsonObj.get("payment_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `payment_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payment_url").toString()));
      }
      if ((jsonObj.get("order_id") != null && !jsonObj.get("order_id").isJsonNull()) && !jsonObj.get("order_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `order_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("order_id").toString()));
      }
      if ((jsonObj.get("customer_email") != null && !jsonObj.get("customer_email").isJsonNull()) && !jsonObj.get("customer_email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customer_email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customer_email").toString()));
      }
      if (jsonObj.get("items") != null && !jsonObj.get("items").isJsonNull()) {
        JsonArray jsonArrayitems = jsonObj.getAsJsonArray("items");
        if (jsonArrayitems != null) {
          // ensure the json data is an array
          if (!jsonObj.get("items").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `items` to be an array in the JSON string but got `%s`", jsonObj.get("items").toString()));
          }

          // validate the optional field `items` (array)
          for (int i = 0; i < jsonArrayitems.size(); i++) {
            LineItem.validateJsonElement(jsonArrayitems.get(i));
          };
        }
      }
      if (jsonObj.get("payments") != null && !jsonObj.get("payments").isJsonNull()) {
        JsonArray jsonArraypayments = jsonObj.getAsJsonArray("payments");
        if (jsonArraypayments != null) {
          // ensure the json data is an array
          if (!jsonObj.get("payments").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `payments` to be an array in the JSON string but got `%s`", jsonObj.get("payments").toString()));
          }

          // validate the optional field `payments` (array)
          for (int i = 0; i < jsonArraypayments.size(); i++) {
            PaymentSplit.validateJsonElement(jsonArraypayments.get(i));
          };
        }
      }
      if ((jsonObj.get("success_url") != null && !jsonObj.get("success_url").isJsonNull()) && !jsonObj.get("success_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `success_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("success_url").toString()));
      }
      if ((jsonObj.get("cancel_url") != null && !jsonObj.get("cancel_url").isJsonNull()) && !jsonObj.get("cancel_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cancel_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cancel_url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Transaction.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Transaction' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Transaction> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Transaction.class));

       return (TypeAdapter<T>) new TypeAdapter<Transaction>() {
           @Override
           public void write(JsonWriter out, Transaction value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Transaction read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Transaction given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Transaction
   * @throws IOException if the JSON string is invalid with respect to Transaction
   */
  public static Transaction fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Transaction.class);
  }

  /**
   * Convert an instance of Transaction to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

