/*
 * CryptoGate API
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package live.cryptogate.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import live.cryptogate.sdk.model.CryptoSymbol;
import live.cryptogate.sdk.model.FiatCurrency;
import live.cryptogate.sdk.model.TransactionStatus;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import live.cryptogate.sdk.JSON;

/**
 * Payment-event payload. AMOUNTS ARE STRINGS (e.g. \&quot;100.00\&quot;, \&quot;0.00109462\&quot;) to preserve decimal precision — parse before arithmetic. 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-27T17:50:21.664603656Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class WebhookPayload {
  /**
   * Gets or Sets event
   */
  @JsonAdapter(EventEnum.Adapter.class)
  public enum EventEnum {
    CREATED("payment.created"),
    
    PENDING("payment.pending"),
    
    COMPLETED("payment.completed"),
    
    OVERPAID("payment.overpaid"),
    
    PARTIAL("payment.partial"),
    
    EXPIRED("payment.expired"),
    
    FAILED("payment.failed");

    private String value;

    EventEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static EventEnum fromValue(String value) {
      for (EventEnum b : EventEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<EventEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final EventEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public EventEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return EventEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      EventEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_EVENT = "event";
  @SerializedName(SERIALIZED_NAME_EVENT)
  @javax.annotation.Nonnull
  private EventEnum event;

  public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  @javax.annotation.Nonnull
  private OffsetDateTime timestamp;

  public static final String SERIALIZED_NAME_TRANSACTION_ID = "transaction_id";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_ID)
  @javax.annotation.Nonnull
  private String transactionId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private TransactionStatus status;

  public static final String SERIALIZED_NAME_CURRENCY_CRYPTO = "currency_crypto";
  @SerializedName(SERIALIZED_NAME_CURRENCY_CRYPTO)
  @javax.annotation.Nullable
  private CryptoSymbol currencyCrypto;

  public static final String SERIALIZED_NAME_CURRENCY_FIAT = "currency_fiat";
  @SerializedName(SERIALIZED_NAME_CURRENCY_FIAT)
  @javax.annotation.Nullable
  private FiatCurrency currencyFiat = FiatCurrency.USD;

  public static final String SERIALIZED_NAME_AMOUNT_FIAT = "amount_fiat";
  @SerializedName(SERIALIZED_NAME_AMOUNT_FIAT)
  @javax.annotation.Nullable
  private String amountFiat;

  public static final String SERIALIZED_NAME_AMOUNT_USD = "amount_usd";
  @SerializedName(SERIALIZED_NAME_AMOUNT_USD)
  @javax.annotation.Nullable
  private String amountUsd;

  public static final String SERIALIZED_NAME_AMOUNT_CRYPTO = "amount_crypto";
  @SerializedName(SERIALIZED_NAME_AMOUNT_CRYPTO)
  @javax.annotation.Nullable
  private String amountCrypto;

  public static final String SERIALIZED_NAME_ORDER_ID = "order_id";
  @SerializedName(SERIALIZED_NAME_ORDER_ID)
  @javax.annotation.Nullable
  private String orderId;

  public static final String SERIALIZED_NAME_RECEIPT_URL = "receipt_url";
  @SerializedName(SERIALIZED_NAME_RECEIPT_URL)
  @javax.annotation.Nullable
  private URI receiptUrl;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  @javax.annotation.Nullable
  private Map<String, String> metadata = new HashMap<>();

  public WebhookPayload() {
  }

  public WebhookPayload event(@javax.annotation.Nonnull EventEnum event) {
    this.event = event;
    return this;
  }

  /**
   * Get event
   * @return event
   */
  @javax.annotation.Nonnull
  public EventEnum getEvent() {
    return event;
  }

  public void setEvent(@javax.annotation.Nonnull EventEnum event) {
    this.event = event;
  }


  public WebhookPayload timestamp(@javax.annotation.Nonnull OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Get timestamp
   * @return timestamp
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(@javax.annotation.Nonnull OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  public WebhookPayload transactionId(@javax.annotation.Nonnull String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

  /**
   * Get transactionId
   * @return transactionId
   */
  @javax.annotation.Nonnull
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(@javax.annotation.Nonnull String transactionId) {
    this.transactionId = transactionId;
  }


  public WebhookPayload status(@javax.annotation.Nonnull TransactionStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public TransactionStatus getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull TransactionStatus status) {
    this.status = status;
  }


  public WebhookPayload currencyCrypto(@javax.annotation.Nullable CryptoSymbol currencyCrypto) {
    this.currencyCrypto = currencyCrypto;
    return this;
  }

  /**
   * Get currencyCrypto
   * @return currencyCrypto
   */
  @javax.annotation.Nullable
  public CryptoSymbol getCurrencyCrypto() {
    return currencyCrypto;
  }

  public void setCurrencyCrypto(@javax.annotation.Nullable CryptoSymbol currencyCrypto) {
    this.currencyCrypto = currencyCrypto;
  }


  public WebhookPayload currencyFiat(@javax.annotation.Nullable FiatCurrency currencyFiat) {
    this.currencyFiat = currencyFiat;
    return this;
  }

  /**
   * Get currencyFiat
   * @return currencyFiat
   */
  @javax.annotation.Nullable
  public FiatCurrency getCurrencyFiat() {
    return currencyFiat;
  }

  public void setCurrencyFiat(@javax.annotation.Nullable FiatCurrency currencyFiat) {
    this.currencyFiat = currencyFiat;
  }


  public WebhookPayload amountFiat(@javax.annotation.Nullable String amountFiat) {
    this.amountFiat = amountFiat;
    return this;
  }

  /**
   * Decimal string.
   * @return amountFiat
   */
  @javax.annotation.Nullable
  public String getAmountFiat() {
    return amountFiat;
  }

  public void setAmountFiat(@javax.annotation.Nullable String amountFiat) {
    this.amountFiat = amountFiat;
  }


  public WebhookPayload amountUsd(@javax.annotation.Nullable String amountUsd) {
    this.amountUsd = amountUsd;
    return this;
  }

  /**
   * Decimal string.
   * @return amountUsd
   */
  @javax.annotation.Nullable
  public String getAmountUsd() {
    return amountUsd;
  }

  public void setAmountUsd(@javax.annotation.Nullable String amountUsd) {
    this.amountUsd = amountUsd;
  }


  public WebhookPayload amountCrypto(@javax.annotation.Nullable String amountCrypto) {
    this.amountCrypto = amountCrypto;
    return this;
  }

  /**
   * Decimal string.
   * @return amountCrypto
   */
  @javax.annotation.Nullable
  public String getAmountCrypto() {
    return amountCrypto;
  }

  public void setAmountCrypto(@javax.annotation.Nullable String amountCrypto) {
    this.amountCrypto = amountCrypto;
  }


  public WebhookPayload orderId(@javax.annotation.Nullable String orderId) {
    this.orderId = orderId;
    return this;
  }

  /**
   * Get orderId
   * @return orderId
   */
  @javax.annotation.Nullable
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(@javax.annotation.Nullable String orderId) {
    this.orderId = orderId;
  }


  public WebhookPayload receiptUrl(@javax.annotation.Nullable URI receiptUrl) {
    this.receiptUrl = receiptUrl;
    return this;
  }

  /**
   * Present on completed/overpaid.
   * @return receiptUrl
   */
  @javax.annotation.Nullable
  public URI getReceiptUrl() {
    return receiptUrl;
  }

  public void setReceiptUrl(@javax.annotation.Nullable URI receiptUrl) {
    this.receiptUrl = receiptUrl;
  }


  public WebhookPayload metadata(@javax.annotation.Nullable Map<String, String> metadata) {
    this.metadata = metadata;
    return this;
  }

  public WebhookPayload putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).
   * @return metadata
   */
  @javax.annotation.Nullable
  public Map<String, String> getMetadata() {
    return metadata;
  }

  public void setMetadata(@javax.annotation.Nullable Map<String, String> metadata) {
    this.metadata = metadata;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookPayload webhookPayload = (WebhookPayload) o;
    return Objects.equals(this.event, webhookPayload.event) &&
        Objects.equals(this.timestamp, webhookPayload.timestamp) &&
        Objects.equals(this.transactionId, webhookPayload.transactionId) &&
        Objects.equals(this.status, webhookPayload.status) &&
        Objects.equals(this.currencyCrypto, webhookPayload.currencyCrypto) &&
        Objects.equals(this.currencyFiat, webhookPayload.currencyFiat) &&
        Objects.equals(this.amountFiat, webhookPayload.amountFiat) &&
        Objects.equals(this.amountUsd, webhookPayload.amountUsd) &&
        Objects.equals(this.amountCrypto, webhookPayload.amountCrypto) &&
        Objects.equals(this.orderId, webhookPayload.orderId) &&
        Objects.equals(this.receiptUrl, webhookPayload.receiptUrl) &&
        Objects.equals(this.metadata, webhookPayload.metadata);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(event, timestamp, transactionId, status, currencyCrypto, currencyFiat, amountFiat, amountUsd, amountCrypto, orderId, receiptUrl, metadata);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookPayload {\n");
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    currencyCrypto: ").append(toIndentedString(currencyCrypto)).append("\n");
    sb.append("    currencyFiat: ").append(toIndentedString(currencyFiat)).append("\n");
    sb.append("    amountFiat: ").append(toIndentedString(amountFiat)).append("\n");
    sb.append("    amountUsd: ").append(toIndentedString(amountUsd)).append("\n");
    sb.append("    amountCrypto: ").append(toIndentedString(amountCrypto)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    receiptUrl: ").append(toIndentedString(receiptUrl)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("event");
    openapiFields.add("timestamp");
    openapiFields.add("transaction_id");
    openapiFields.add("status");
    openapiFields.add("currency_crypto");
    openapiFields.add("currency_fiat");
    openapiFields.add("amount_fiat");
    openapiFields.add("amount_usd");
    openapiFields.add("amount_crypto");
    openapiFields.add("order_id");
    openapiFields.add("receipt_url");
    openapiFields.add("metadata");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("event");
    openapiRequiredFields.add("timestamp");
    openapiRequiredFields.add("transaction_id");
    openapiRequiredFields.add("status");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WebhookPayload
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WebhookPayload.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WebhookPayload is not found in the empty JSON string", WebhookPayload.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WebhookPayload.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `WebhookPayload` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : WebhookPayload.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("event").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `event` to be a primitive type in the JSON string but got `%s`", jsonObj.get("event").toString()));
      }
      // validate the required field `event`
      EventEnum.validateJsonElement(jsonObj.get("event"));
      if (!jsonObj.get("transaction_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `transaction_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transaction_id").toString()));
      }
      // validate the required field `status`
      TransactionStatus.validateJsonElement(jsonObj.get("status"));
      // validate the optional field `currency_crypto`
      if (jsonObj.get("currency_crypto") != null && !jsonObj.get("currency_crypto").isJsonNull()) {
        CryptoSymbol.validateJsonElement(jsonObj.get("currency_crypto"));
      }
      // validate the optional field `currency_fiat`
      if (jsonObj.get("currency_fiat") != null && !jsonObj.get("currency_fiat").isJsonNull()) {
        FiatCurrency.validateJsonElement(jsonObj.get("currency_fiat"));
      }
      if ((jsonObj.get("amount_fiat") != null && !jsonObj.get("amount_fiat").isJsonNull()) && !jsonObj.get("amount_fiat").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `amount_fiat` to be a primitive type in the JSON string but got `%s`", jsonObj.get("amount_fiat").toString()));
      }
      if ((jsonObj.get("amount_usd") != null && !jsonObj.get("amount_usd").isJsonNull()) && !jsonObj.get("amount_usd").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `amount_usd` to be a primitive type in the JSON string but got `%s`", jsonObj.get("amount_usd").toString()));
      }
      if ((jsonObj.get("amount_crypto") != null && !jsonObj.get("amount_crypto").isJsonNull()) && !jsonObj.get("amount_crypto").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `amount_crypto` to be a primitive type in the JSON string but got `%s`", jsonObj.get("amount_crypto").toString()));
      }
      if ((jsonObj.get("order_id") != null && !jsonObj.get("order_id").isJsonNull()) && !jsonObj.get("order_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `order_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("order_id").toString()));
      }
      if ((jsonObj.get("receipt_url") != null && !jsonObj.get("receipt_url").isJsonNull()) && !jsonObj.get("receipt_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `receipt_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("receipt_url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WebhookPayload.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WebhookPayload' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WebhookPayload> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WebhookPayload.class));

       return (TypeAdapter<T>) new TypeAdapter<WebhookPayload>() {
           @Override
           public void write(JsonWriter out, WebhookPayload value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WebhookPayload read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WebhookPayload given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WebhookPayload
   * @throws IOException if the JSON string is invalid with respect to WebhookPayload
   */
  public static WebhookPayload fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WebhookPayload.class);
  }

  /**
   * Convert an instance of WebhookPayload to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

