/*
 * CryptoGate API
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…`, or `sk_test_…` for sandbox). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package live.cryptogate.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import live.cryptogate.sdk.model.CryptoSymbol;
import live.cryptogate.sdk.model.FiatCurrency;
import live.cryptogate.sdk.model.LineItem;
import live.cryptogate.sdk.model.PaymentSplit;
import live.cryptogate.sdk.model.TransactionStatus;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Transaction
 */
public class TransactionTest {
    private final Transaction model = new Transaction();

    /**
     * Model tests for Transaction
     */
    @Test
    public void testTransaction() {
        // TODO: test Transaction
    }

    /**
     * Test the property 'transactionId'
     */
    @Test
    public void transactionIdTest() {
        // TODO: test transactionId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'crypto'
     */
    @Test
    public void cryptoTest() {
        // TODO: test crypto
    }

    /**
     * Test the property 'depositAddress'
     */
    @Test
    public void depositAddressTest() {
        // TODO: test depositAddress
    }

    /**
     * Test the property 'amountCrypto'
     */
    @Test
    public void amountCryptoTest() {
        // TODO: test amountCrypto
    }

    /**
     * Test the property 'amountFiat'
     */
    @Test
    public void amountFiatTest() {
        // TODO: test amountFiat
    }

    /**
     * Test the property 'amountUsd'
     */
    @Test
    public void amountUsdTest() {
        // TODO: test amountUsd
    }

    /**
     * Test the property 'amountPaid'
     */
    @Test
    public void amountPaidTest() {
        // TODO: test amountPaid
    }

    /**
     * Test the property 'amountRemaining'
     */
    @Test
    public void amountRemainingTest() {
        // TODO: test amountRemaining
    }

    /**
     * Test the property 'currencyFiat'
     */
    @Test
    public void currencyFiatTest() {
        // TODO: test currencyFiat
    }

    /**
     * Test the property 'fiatToUsdRate'
     */
    @Test
    public void fiatToUsdRateTest() {
        // TODO: test fiatToUsdRate
    }

    /**
     * Test the property 'exchangeRate'
     */
    @Test
    public void exchangeRateTest() {
        // TODO: test exchangeRate
    }

    /**
     * Test the property 'confirmationsRequired'
     */
    @Test
    public void confirmationsRequiredTest() {
        // TODO: test confirmationsRequired
    }

    /**
     * Test the property 'paymentUrl'
     */
    @Test
    public void paymentUrlTest() {
        // TODO: test paymentUrl
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    public void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'customerEmail'
     */
    @Test
    public void customerEmailTest() {
        // TODO: test customerEmail
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'payments'
     */
    @Test
    public void paymentsTest() {
        // TODO: test payments
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'successUrl'
     */
    @Test
    public void successUrlTest() {
        // TODO: test successUrl
    }

    /**
     * Test the property 'cancelUrl'
     */
    @Test
    public void cancelUrlTest() {
        // TODO: test cancelUrl
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    public void expiresAtTest() {
        // TODO: test expiresAt
    }

}
