/*
 * GriffNode API
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.griffnode.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.griffnode.sdk.model.PlanTier;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Plan
 */
public class PlanTest {
    private final Plan model = new Plan();

    /**
     * Model tests for Plan
     */
    @Test
    public void testPlan() {
        // TODO: test Plan
    }

    /**
     * Test the property 'tier'
     */
    @Test
    public void tierTest() {
        // TODO: test tier
    }

    /**
     * Test the property 'monthlyPriceUsd'
     */
    @Test
    public void monthlyPriceUsdTest() {
        // TODO: test monthlyPriceUsd
    }

    /**
     * Test the property 'yearlyPriceUsd'
     */
    @Test
    public void yearlyPriceUsdTest() {
        // TODO: test yearlyPriceUsd
    }

    /**
     * Test the property 'monthlyTransactionLimit'
     */
    @Test
    public void monthlyTransactionLimitTest() {
        // TODO: test monthlyTransactionLimit
    }

    /**
     * Test the property 'overageCostPerTx'
     */
    @Test
    public void overageCostPerTxTest() {
        // TODO: test overageCostPerTx
    }

    /**
     * Test the property 'webhookSupport'
     */
    @Test
    public void webhookSupportTest() {
        // TODO: test webhookSupport
    }

    /**
     * Test the property 'webhookLimit'
     */
    @Test
    public void webhookLimitTest() {
        // TODO: test webhookLimit
    }

    /**
     * Test the property 'ipWhitelist'
     */
    @Test
    public void ipWhitelistTest() {
        // TODO: test ipWhitelist
    }

    /**
     * Test the property 'apiRateLimitPerMinute'
     */
    @Test
    public void apiRateLimitPerMinuteTest() {
        // TODO: test apiRateLimitPerMinute
    }

    /**
     * Test the property 'apiRateLimitPerHour'
     */
    @Test
    public void apiRateLimitPerHourTest() {
        // TODO: test apiRateLimitPerHour
    }

    /**
     * Test the property 'customPricing'
     */
    @Test
    public void customPricingTest() {
        // TODO: test customPricing
    }

}
