/*
 * GriffNode API
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.griffnode.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.griffnode.sdk.JSON;

/**
 * AccountUsage
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-08T10:52:29.110714780Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class AccountUsage {
  public static final String SERIALIZED_NAME_MONTHLY_TRANSACTIONS_USED = "monthly_transactions_used";
  @SerializedName(SERIALIZED_NAME_MONTHLY_TRANSACTIONS_USED)
  @javax.annotation.Nullable
  private Integer monthlyTransactionsUsed;

  public static final String SERIALIZED_NAME_MONTHLY_TRANSACTION_LIMIT = "monthly_transaction_limit";
  @SerializedName(SERIALIZED_NAME_MONTHLY_TRANSACTION_LIMIT)
  @javax.annotation.Nullable
  private Integer monthlyTransactionLimit;

  public static final String SERIALIZED_NAME_OVERAGE_COST_PER_TX = "overage_cost_per_tx";
  @SerializedName(SERIALIZED_NAME_OVERAGE_COST_PER_TX)
  @javax.annotation.Nullable
  private BigDecimal overageCostPerTx;

  public AccountUsage() {
  }

  public AccountUsage monthlyTransactionsUsed(@javax.annotation.Nullable Integer monthlyTransactionsUsed) {
    this.monthlyTransactionsUsed = monthlyTransactionsUsed;
    return this;
  }

  /**
   * Get monthlyTransactionsUsed
   * @return monthlyTransactionsUsed
   */
  @javax.annotation.Nullable
  public Integer getMonthlyTransactionsUsed() {
    return monthlyTransactionsUsed;
  }

  public void setMonthlyTransactionsUsed(@javax.annotation.Nullable Integer monthlyTransactionsUsed) {
    this.monthlyTransactionsUsed = monthlyTransactionsUsed;
  }


  public AccountUsage monthlyTransactionLimit(@javax.annotation.Nullable Integer monthlyTransactionLimit) {
    this.monthlyTransactionLimit = monthlyTransactionLimit;
    return this;
  }

  /**
   * null &#x3D; unlimited.
   * @return monthlyTransactionLimit
   */
  @javax.annotation.Nullable
  public Integer getMonthlyTransactionLimit() {
    return monthlyTransactionLimit;
  }

  public void setMonthlyTransactionLimit(@javax.annotation.Nullable Integer monthlyTransactionLimit) {
    this.monthlyTransactionLimit = monthlyTransactionLimit;
  }


  public AccountUsage overageCostPerTx(@javax.annotation.Nullable BigDecimal overageCostPerTx) {
    this.overageCostPerTx = overageCostPerTx;
    return this;
  }

  /**
   * Get overageCostPerTx
   * @return overageCostPerTx
   */
  @javax.annotation.Nullable
  public BigDecimal getOverageCostPerTx() {
    return overageCostPerTx;
  }

  public void setOverageCostPerTx(@javax.annotation.Nullable BigDecimal overageCostPerTx) {
    this.overageCostPerTx = overageCostPerTx;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountUsage accountUsage = (AccountUsage) o;
    return Objects.equals(this.monthlyTransactionsUsed, accountUsage.monthlyTransactionsUsed) &&
        Objects.equals(this.monthlyTransactionLimit, accountUsage.monthlyTransactionLimit) &&
        Objects.equals(this.overageCostPerTx, accountUsage.overageCostPerTx);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(monthlyTransactionsUsed, monthlyTransactionLimit, overageCostPerTx);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountUsage {\n");
    sb.append("    monthlyTransactionsUsed: ").append(toIndentedString(monthlyTransactionsUsed)).append("\n");
    sb.append("    monthlyTransactionLimit: ").append(toIndentedString(monthlyTransactionLimit)).append("\n");
    sb.append("    overageCostPerTx: ").append(toIndentedString(overageCostPerTx)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("monthly_transactions_used");
    openapiFields.add("monthly_transaction_limit");
    openapiFields.add("overage_cost_per_tx");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AccountUsage
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AccountUsage.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AccountUsage is not found in the empty JSON string", AccountUsage.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AccountUsage.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AccountUsage` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AccountUsage.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AccountUsage' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AccountUsage> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AccountUsage.class));

       return (TypeAdapter<T>) new TypeAdapter<AccountUsage>() {
           @Override
           public void write(JsonWriter out, AccountUsage value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AccountUsage read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AccountUsage given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AccountUsage
   * @throws IOException if the JSON string is invalid with respect to AccountUsage
   */
  public static AccountUsage fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AccountUsage.class);
  }

  /**
   * Convert an instance of AccountUsage to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

