/*
 * GriffNode API
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.griffnode.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.griffnode.sdk.model.CryptoSymbol;
import com.griffnode.sdk.model.FiatCurrency;
import com.griffnode.sdk.model.LineItem;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.griffnode.sdk.JSON;

/**
 * CreateDetailedTransactionRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-07T18:22:47.622078015Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class CreateDetailedTransactionRequest {
  public static final String SERIALIZED_NAME_CRYPTO = "crypto";
  @SerializedName(SERIALIZED_NAME_CRYPTO)
  @javax.annotation.Nonnull
  private CryptoSymbol crypto;

  public static final String SERIALIZED_NAME_CURRENCY_FIAT = "currency_fiat";
  @SerializedName(SERIALIZED_NAME_CURRENCY_FIAT)
  @javax.annotation.Nullable
  private FiatCurrency currencyFiat = FiatCurrency.USD;

  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  @javax.annotation.Nonnull
  private List<LineItem> items = new ArrayList<>();

  public static final String SERIALIZED_NAME_ORDER_ID = "order_id";
  @SerializedName(SERIALIZED_NAME_ORDER_ID)
  @javax.annotation.Nonnull
  private String orderId;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  @javax.annotation.Nullable
  private Map<String, String> metadata = new HashMap<>();

  public static final String SERIALIZED_NAME_CUSTOMER_EMAIL = "customer_email";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_EMAIL)
  @javax.annotation.Nullable
  private String customerEmail;

  public static final String SERIALIZED_NAME_SUCCESS_URL = "success_url";
  @SerializedName(SERIALIZED_NAME_SUCCESS_URL)
  @javax.annotation.Nullable
  private URI successUrl;

  public static final String SERIALIZED_NAME_CANCEL_URL = "cancel_url";
  @SerializedName(SERIALIZED_NAME_CANCEL_URL)
  @javax.annotation.Nullable
  private URI cancelUrl;

  public CreateDetailedTransactionRequest() {
  }

  public CreateDetailedTransactionRequest crypto(@javax.annotation.Nonnull CryptoSymbol crypto) {
    this.crypto = crypto;
    return this;
  }

  /**
   * Get crypto
   * @return crypto
   */
  @javax.annotation.Nonnull
  public CryptoSymbol getCrypto() {
    return crypto;
  }

  public void setCrypto(@javax.annotation.Nonnull CryptoSymbol crypto) {
    this.crypto = crypto;
  }


  public CreateDetailedTransactionRequest currencyFiat(@javax.annotation.Nullable FiatCurrency currencyFiat) {
    this.currencyFiat = currencyFiat;
    return this;
  }

  /**
   * Get currencyFiat
   * @return currencyFiat
   */
  @javax.annotation.Nullable
  public FiatCurrency getCurrencyFiat() {
    return currencyFiat;
  }

  public void setCurrencyFiat(@javax.annotation.Nullable FiatCurrency currencyFiat) {
    this.currencyFiat = currencyFiat;
  }


  public CreateDetailedTransactionRequest items(@javax.annotation.Nonnull List<LineItem> items) {
    this.items = items;
    return this;
  }

  public CreateDetailedTransactionRequest addItemsItem(LineItem itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * Get items
   * @return items
   */
  @javax.annotation.Nonnull
  public List<LineItem> getItems() {
    return items;
  }

  public void setItems(@javax.annotation.Nonnull List<LineItem> items) {
    this.items = items;
  }


  public CreateDetailedTransactionRequest orderId(@javax.annotation.Nonnull String orderId) {
    this.orderId = orderId;
    return this;
  }

  /**
   * Get orderId
   * @return orderId
   */
  @javax.annotation.Nonnull
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(@javax.annotation.Nonnull String orderId) {
    this.orderId = orderId;
  }


  public CreateDetailedTransactionRequest metadata(@javax.annotation.Nullable Map<String, String> metadata) {
    this.metadata = metadata;
    return this;
  }

  public CreateDetailedTransactionRequest putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).
   * @return metadata
   */
  @javax.annotation.Nullable
  public Map<String, String> getMetadata() {
    return metadata;
  }

  public void setMetadata(@javax.annotation.Nullable Map<String, String> metadata) {
    this.metadata = metadata;
  }


  public CreateDetailedTransactionRequest customerEmail(@javax.annotation.Nullable String customerEmail) {
    this.customerEmail = customerEmail;
    return this;
  }

  /**
   * Get customerEmail
   * @return customerEmail
   */
  @javax.annotation.Nullable
  public String getCustomerEmail() {
    return customerEmail;
  }

  public void setCustomerEmail(@javax.annotation.Nullable String customerEmail) {
    this.customerEmail = customerEmail;
  }


  public CreateDetailedTransactionRequest successUrl(@javax.annotation.Nullable URI successUrl) {
    this.successUrl = successUrl;
    return this;
  }

  /**
   * Get successUrl
   * @return successUrl
   */
  @javax.annotation.Nullable
  public URI getSuccessUrl() {
    return successUrl;
  }

  public void setSuccessUrl(@javax.annotation.Nullable URI successUrl) {
    this.successUrl = successUrl;
  }


  public CreateDetailedTransactionRequest cancelUrl(@javax.annotation.Nullable URI cancelUrl) {
    this.cancelUrl = cancelUrl;
    return this;
  }

  /**
   * Get cancelUrl
   * @return cancelUrl
   */
  @javax.annotation.Nullable
  public URI getCancelUrl() {
    return cancelUrl;
  }

  public void setCancelUrl(@javax.annotation.Nullable URI cancelUrl) {
    this.cancelUrl = cancelUrl;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateDetailedTransactionRequest createDetailedTransactionRequest = (CreateDetailedTransactionRequest) o;
    return Objects.equals(this.crypto, createDetailedTransactionRequest.crypto) &&
        Objects.equals(this.currencyFiat, createDetailedTransactionRequest.currencyFiat) &&
        Objects.equals(this.items, createDetailedTransactionRequest.items) &&
        Objects.equals(this.orderId, createDetailedTransactionRequest.orderId) &&
        Objects.equals(this.metadata, createDetailedTransactionRequest.metadata) &&
        Objects.equals(this.customerEmail, createDetailedTransactionRequest.customerEmail) &&
        Objects.equals(this.successUrl, createDetailedTransactionRequest.successUrl) &&
        Objects.equals(this.cancelUrl, createDetailedTransactionRequest.cancelUrl);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(crypto, currencyFiat, items, orderId, metadata, customerEmail, successUrl, cancelUrl);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateDetailedTransactionRequest {\n");
    sb.append("    crypto: ").append(toIndentedString(crypto)).append("\n");
    sb.append("    currencyFiat: ").append(toIndentedString(currencyFiat)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    customerEmail: ").append(toIndentedString(customerEmail)).append("\n");
    sb.append("    successUrl: ").append(toIndentedString(successUrl)).append("\n");
    sb.append("    cancelUrl: ").append(toIndentedString(cancelUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("crypto");
    openapiFields.add("currency_fiat");
    openapiFields.add("items");
    openapiFields.add("order_id");
    openapiFields.add("metadata");
    openapiFields.add("customer_email");
    openapiFields.add("success_url");
    openapiFields.add("cancel_url");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("crypto");
    openapiRequiredFields.add("items");
    openapiRequiredFields.add("order_id");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateDetailedTransactionRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateDetailedTransactionRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateDetailedTransactionRequest is not found in the empty JSON string", CreateDetailedTransactionRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateDetailedTransactionRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateDetailedTransactionRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateDetailedTransactionRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `crypto`
      CryptoSymbol.validateJsonElement(jsonObj.get("crypto"));
      // validate the optional field `currency_fiat`
      if (jsonObj.get("currency_fiat") != null && !jsonObj.get("currency_fiat").isJsonNull()) {
        FiatCurrency.validateJsonElement(jsonObj.get("currency_fiat"));
      }
      // ensure the json data is an array
      if (!jsonObj.get("items").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `items` to be an array in the JSON string but got `%s`", jsonObj.get("items").toString()));
      }

      JsonArray jsonArrayitems = jsonObj.getAsJsonArray("items");
      // validate the required field `items` (array)
      for (int i = 0; i < jsonArrayitems.size(); i++) {
        LineItem.validateJsonElement(jsonArrayitems.get(i));
      };
      if (!jsonObj.get("order_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `order_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("order_id").toString()));
      }
      if ((jsonObj.get("customer_email") != null && !jsonObj.get("customer_email").isJsonNull()) && !jsonObj.get("customer_email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customer_email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customer_email").toString()));
      }
      if ((jsonObj.get("success_url") != null && !jsonObj.get("success_url").isJsonNull()) && !jsonObj.get("success_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `success_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("success_url").toString()));
      }
      if ((jsonObj.get("cancel_url") != null && !jsonObj.get("cancel_url").isJsonNull()) && !jsonObj.get("cancel_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cancel_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cancel_url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateDetailedTransactionRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateDetailedTransactionRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateDetailedTransactionRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateDetailedTransactionRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateDetailedTransactionRequest>() {
           @Override
           public void write(JsonWriter out, CreateDetailedTransactionRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateDetailedTransactionRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateDetailedTransactionRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateDetailedTransactionRequest
   * @throws IOException if the JSON string is invalid with respect to CreateDetailedTransactionRequest
   */
  public static CreateDetailedTransactionRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateDetailedTransactionRequest.class);
  }

  /**
   * Convert an instance of CreateDetailedTransactionRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

