/*
 * GriffNode API
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.griffnode.sdk.api;

import com.griffnode.sdk.ApiCallback;
import com.griffnode.sdk.ApiClient;
import com.griffnode.sdk.ApiException;
import com.griffnode.sdk.ApiResponse;
import com.griffnode.sdk.Configuration;
import com.griffnode.sdk.Pair;
import com.griffnode.sdk.ProgressRequestBody;
import com.griffnode.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.griffnode.sdk.model.CreateBillingCheckoutRequest;
import com.griffnode.sdk.model.Error;
import com.griffnode.sdk.model.TransactionEnvelope;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BillingApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public BillingApi() {
        this(Configuration.getDefaultApiClient());
    }

    public BillingApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createBillingCheckout
     * @param createBillingCheckoutRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Billing transaction created. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 402 </td><td> Merchant platform balance too low for overage fees (INSUFFICIENT_BALANCE). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createBillingCheckoutCall(CreateBillingCheckoutRequest createBillingCheckoutRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createBillingCheckoutRequest;

        // create path and map variables
        String localVarPath = "/billing/checkout";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "SecretKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createBillingCheckoutValidateBeforeCall(CreateBillingCheckoutRequest createBillingCheckoutRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createBillingCheckoutRequest' is set
        if (createBillingCheckoutRequest == null) {
            throw new ApiException("Missing the required parameter 'createBillingCheckoutRequest' when calling createBillingCheckout(Async)");
        }

        return createBillingCheckoutCall(createBillingCheckoutRequest, _callback);

    }

    /**
     * Start a plan upgrade or account top-up
     * 
     * @param createBillingCheckoutRequest  (required)
     * @return TransactionEnvelope
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Billing transaction created. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 402 </td><td> Merchant platform balance too low for overage fees (INSUFFICIENT_BALANCE). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public TransactionEnvelope createBillingCheckout(CreateBillingCheckoutRequest createBillingCheckoutRequest) throws ApiException {
        ApiResponse<TransactionEnvelope> localVarResp = createBillingCheckoutWithHttpInfo(createBillingCheckoutRequest);
        return localVarResp.getData();
    }

    /**
     * Start a plan upgrade or account top-up
     * 
     * @param createBillingCheckoutRequest  (required)
     * @return ApiResponse&lt;TransactionEnvelope&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Billing transaction created. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 402 </td><td> Merchant platform balance too low for overage fees (INSUFFICIENT_BALANCE). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TransactionEnvelope> createBillingCheckoutWithHttpInfo(CreateBillingCheckoutRequest createBillingCheckoutRequest) throws ApiException {
        okhttp3.Call localVarCall = createBillingCheckoutValidateBeforeCall(createBillingCheckoutRequest, null);
        Type localVarReturnType = new TypeToken<TransactionEnvelope>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Start a plan upgrade or account top-up (asynchronously)
     * 
     * @param createBillingCheckoutRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Billing transaction created. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid API key (UNAUTHORIZED). </td><td>  -  </td></tr>
        <tr><td> 402 </td><td> Merchant platform balance too low for overage fees (INSUFFICIENT_BALANCE). </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Key lacks permission — e.g. a publishable key on a secret-only endpoint, or plan too low (FORBIDDEN, USE_PAY_ENDPOINT, PLAN_UPGRADE_REQUIRED, NO_ACTIVE_PLAN). </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createBillingCheckoutAsync(CreateBillingCheckoutRequest createBillingCheckoutRequest, final ApiCallback<TransactionEnvelope> _callback) throws ApiException {

        okhttp3.Call localVarCall = createBillingCheckoutValidateBeforeCall(createBillingCheckoutRequest, _callback);
        Type localVarReturnType = new TypeToken<TransactionEnvelope>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
